service: app

provider:
  name: aws
  region: us-west-2
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref

functions:
  hello:
    handler: index.php
    description: ""
    layers:
      - ${bref:layer.php-81}

# Exclude files from deployment
package:
  patterns:
    - "!tests/**"
